#!/usr/bin/env bash

# GTK
sed -i '5s_gtk-theme-name=.*_gtk-theme-name="ZorinBlue"_' ~/.gtkrc-2.0
sed -i '10s_gtk-theme-name=.*_gtk-theme-name=ZorinBlue_' ~/.config/gtk-3.0/settings.ini

# Icon
sed -i '6s_gtk-icon-theme-name=.*_gtk-icon-theme-name="oomox-aesthetic-light"_' ~/.gtkrc-2.0
sed -i '8s_gtk-icon-theme-name=.*_gtk-icon-theme-name=oomox-aesthetic-light_' ~/.config/gtk-3.0/settings.ini
sed -i '4s\icon_theme=.*\icon_theme=oomox-aesthetic-light\' ~/.config/qt5ct/qt5ct.conf

# Rofi
sed -i '1s_colorschemes/.*.rasi_colorschemes/color-light.rasi_' ~/.config/rofi/themes/shared/settings.rasi
