#!/usr/bin/env bash

# Load Global Variable
source $HOME/.aether-corevar

# Color Variable
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}-----------------------------------------------${NC}"
echo -e "Example : ${GREEN}/home/user/Pictures/image.jpg${NC}"
echo -e "Use ${YELLOW}DEFAULT${NC} to use both theme default wallpaper"
echo -e "${CYAN}-----------------------------------------------${NC}"
read -p "Input : " -i "$HOME/" -e IMGPATH
sed -i '10s|WALLPAPER=.*|WALLPAPER="'$IMGPATH'"|' ~/.aether-corevar && ~/.config/aether/scripts/wallpaper &>/dev/null

if [[ ! "$?" = "0" ]]; then
    echo -e "${RED}wallpaper${NC}          | ${RED}*${NC} ERROR: invalid path/file"
    sleep 1
    $NOTIFIER -r 14 -i "$ICONDIR/wallpaper.png" -t 2500 -u low "Error Occured" "Change Wallpaper"
    exit 1
fi

if [[ $IMGPATH == "DEFAULT" ]]; then
    $NOTIFIER -r 14 -i "$ICONDIR/wallpaper.png" -t 1500 -u low "Change Wallpaper" "Default Theme"
else
    $NOTIFIER -r 14 -i "$ICONDIR/wallpaper.png" -t 1500 -u low "Change Wallpaper" "$IMGPATH"
fi

echo -e "${CYAN}wallpaper${NC}          | ${GREEN}*${NC} Changing wallpaper ...                  ${BLUE}[${GREEN} ok ${BLUE}]${NC}"

sleep 1